# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

extends: eslint:recommended

parser: babel-eslint

env:
    browser: true
    es6: true
    jest: true

ecmaFeatures:
    classes: true
    experimentalObjectRestSpread: true
    jsx: true
    modules: true
    templateStrings: true

globals:
    new: true
    process: true
    require: true
    target: true

plugins:
    - react

rules:
    arrow-body-style:
        - 2
        - always
    indent:
        - 2
        - 2
        -
            SwitchCase: 1
    quotes:
        - 2
        - single
    linebreak-style:
        - 2
        - unix
    semi:
        - 2
        - always
    no-unused-vars:
        - 2
        -
            vars: all
            args: after-used
    block-scoped-var: 2
    brace-style: 2
    camelcase: 0
    comma-dangle: 0
    comma-spacing: 2
    comma-style: 2
    complexity:
        - 0
        - 11
    consistent-return: 2
    curly:
        - 2
        - all
    default-case: 0
    dot-notation:
        - 2
        -
            allowKeywords: true
    eol-last: 2
    eqeqeq: 2
    func-names: 0
    func-style:
        - 2
        - declaration
    generator-star: 0
    guard-for-in: 0
    handle-callback-err: 2
    key-spacing:
        - 2
        -
            beforeColon: false
            afterColon: true
    max-depth:
        - 1
        - 4
    max-len:
        - 2
        - 120
    max-nested-callbacks:
        - 1
        - 2
    max-params:
        - 1
        - 4
    max-statements:
        - 0
        - 10
    new-cap: 2
    new-parens: 2
    no-alert: 2
    no-array-constructor: 2
    no-arrow-condition: 2
    no-bitwise: 0
    no-caller: 2
    no-catch-shadow: 2
    no-cond-assign:
        - 2
        - always
    no-console: 0
    no-constant-condition: 2
    no-control-regex: 2
    no-debugger: 2
    no-delete-var: 2
    no-div-regex: 0
    no-dupe-keys: 2
    no-else-return: 2
    no-empty: 2
    no-empty-character-class: 2
    no-empty-label: 2
    no-eq-null: 2
    no-eval: 2
    no-ex-assign: 2
    no-extend-native: 2
    no-extra-bind: 2
    no-extra-boolean-cast: 2
    no-extra-parens:
        - 2
        - functions
    no-extra-semi: 2
    no-fallthrough: 2
    no-floating-decimal: 0
    no-func-assign: 2
    no-implied-eval: 2
    no-inline-comments: 0
    no-inner-declarations:
        - 2
        - functions
    no-invalid-regexp: 2
    no-irregular-whitespace: 2
    no-iterator: 2
    no-label-var: 2
    no-labels: 2
    no-lone-blocks: 2
    no-lonely-if: 2
    no-loop-func: 2
    no-mixed-requires:
        - 0
        - false
    no-mixed-spaces-and-tabs:
        - 2
        - false
    no-multi-spaces: 2
    no-multi-str: 2
    no-multiple-empty-lines:
        - 2
        -
            max: 2
    no-native-reassign: 2
    no-negated-in-lhs: 2
    no-nested-ternary: 0
    no-new: 0
    no-new-func: 2
    no-new-object: 2
    no-new-require: 0
    no-new-wrappers: 2
    no-obj-calls: 2
    no-octal: 2
    no-octal-escape: 2
    no-path-concat: 0
    no-plusplus: 0
    no-process-env: 0
    no-process-exit: 0
    no-proto: 2
    no-redeclare: 2
    no-regex-spaces: 2
    no-reserved-keys: 0
    no-restricted-modules: 0
    no-return-assign: 2
    no-script-url: 2
    no-self-compare: 2
    no-sequences: 2
    no-shadow: 2
    no-shadow-restricted-names: 2
    no-spaced-func: 2
    no-sparse-arrays: 2
    no-sync: 0
    no-ternary: 0
    no-trailing-spaces: 2
    no-undef: 2
    no-undef-init: 2
    no-undefined: 0
    no-underscore-dangle: 0
    no-unreachable: 2
    no-unused-expressions: 2
    no-unused-vars:
        - 2
        -
            vars: all
            args: after-used
    no-use-before-define: 2
    no-void: 2
    no-var: 0
    no-warning-comments:
        - 0
        -
            terms:
                - todo
                - fixme
                - xxx
            location: start
    no-with: 2
    one-var: 2
    operator-assignment:
        - 0
        - always
    padded-blocks: 0
    quote-props: 0
    quotes:
        - 2
        - single
    radix: 2
    sort-vars: 0
    space-after-function-name:
        - 0
        - never
    space-after-keywords: 2
    space-before-blocks: 2
    space-in-parens: 2
    space-infix-ops: 2
    space-return-throw-case: 2
    space-unary-ops:
        - 2
        -
            words: true
            nonwords: false
    spaced-comment: 2
    strict:
        - 2
        - global
    use-isnan: 2
    valid-jsdoc: 2
    valid-typeof: 2
    vars-on-top: 0
    wrap-iife: 0
    wrap-regex: 0
    yoda: 0

###############################
########### ES2015 ############
###############################
    arrow-parens: 2
    arrow-spacing:
        - 2
        -
            before: true
            after: true
    constructor-super: 2
    generator-star-spacing: 2
    no-class-assign: 2
    no-const-assign: 2
    no-dupe-class-members: 2
    no-this-before-super: 0
    object-shorthand:
        - 2
        - always
    prefer-arrow-callback: 2
    prefer-const: 2
    prefer-spread: 2
    prefer-reflect: 2
    prefer-template: 2
    require-yield: 2

###############################
########### REACT #############
###############################
    react/display-name: 0
    react/forbid-prop-types: 0
    react/jsx-boolean-value: 0
    react/jsx-closing-bracket-location: 0
    react/jsx-curly-spacing: 0
    react/jsx-indent-props: 0
    react/jsx-max-props-per-line: 0
    react/jsx-no-duplicate-props: 1
    react/jsx-no-literals: 0
    react/jsx-no-undef: 1
    jsx-quotes: 1
    react/jsx-sort-prop-types: 1
    react/jsx-sort-props: 1
    react/jsx-uses-react: 1
    react/jsx-uses-vars: 1
    react/no-danger: 1
    react/no-did-mount-set-state: 1
    react/no-did-update-set-state: 1
    react/no-direct-mutation-state: 1
    react/no-multi-comp: 1
    react/no-set-state: 0
    react/no-unknown-property: 1
    react/prop-types: 0
    react/react-in-jsx-scope: 0
    react/require-extension: 0
    react/self-closing-comp: 0
    react/sort-comp: 0
    react/wrap-multilines: 0
