# This file belongs to Kreta.
# The source code of application includes a LICENSE file
# with all information about license.
#
# @author benatespina <benatespina@gmail.com>
# @author gorkalaucirica <gorka.lauzirika@gmail.com>

language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

env:
    - COMPOSER_OPTIONS="--prefer-source"

before_install:
    - sudo apt-get update
    - sudo apt-get -qq install ruby-sass

install:
    - composer update --no-interaction ${COMPOSER_OPTIONS}

    - sudo apt-get install node
    - npm install -g bower
    - npm install -g gulp
    - gem install scss-lint

    - cd Bundle/WebBundle
    - npm install
    - bower install
    - cd -

before_script:
    - app/console assets:install --symlink
    - cd Bundle/WebBundle
    - gulp
    - cd -

    - sleep 5

script:
    - bin/phpspec run -fpretty

after_script:
    - bin/coveralls -v

cache:
    directories:
        - $COMPOSER_CACHE_DIR

matrix:
    fast_finish: true
    allow_failures:
        - php: 7.0
        - php: hhvm
    include:
        - php: 5.4
          env: COMPOSER_OPTIONS="--prefer-lowest"
