# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

addons:
    hosts:
        - kreta.test

language: php

php:
    - 7.0

env:
    - COMPOSER_OPTIONS="--prefer-source"

install:
    - composer self-update
    - composer update --no-interaction ${COMPOSER_OPTIONS}

before_script:
    - export SYMFONY_ENV=test
    - TaskManager/src/Infrastructure/Ui/Cli/Symfony/console server:start kreta.test:8001 --router=TaskManager/src/Infrastructure/Ui/Http/Symfony/public/app.php --docroot=TaskManager/src/Infrastructure/Ui/Http/Symfony/public
    - sleep 5

script:
    - vendor/bin/phpspec run

cache:
    directories:
        - $COMPOSER_CACHE_DIR

matrix:
    fast_finish: true
