# This file belongs to Kreta.
# The source code of application includes a LICENSE file
# with all information about license.
#
# @author benatespina <benatespina@gmail.com>
# @author gorkalaucirica <gorka.lauzirika@gmail.com>

Kreta\Component\Project\Model\Participant:
    exclusion_policy: ALL
    relations:
        -
            rel: participants
            href:
                route: get_projects_participants
                parameters:
                    projectId: expr(object.getProject().getId())
                absolute: true
            exclusion:
                groups: [participantList, participant]
        -
            rel: project
            href:
                route: get_project
                parameters:
                    projectId: expr(object.getProject().getId())
                absolute: true
            exclusion:
                groups: [participantList, participant]
        -
            rel: projects
            href:
                route: get_projects
                absolute: true
            exclusion:
                groups: [participantList, participant]
        -
            rel: issues
            href:
                route: get_issues
                absolute: true
            exclusion:
                groups: [participantList, participant]
    properties:
        project:
            expose: true
            groups: [projectList, project, participantList, participant]
        user:
            expose: true
            groups: [projectList, project, participantList, participant]
        role:
            expose: true
            groups: [projectList, project, participantList, participant]
