# This file belongs to Kreta.
# The source code of application includes a LICENSE file
# with all information about license.
#
# @author benatespina <benatespina@gmail.com>
# @author gorkalaucirica <gorka.lauzirika@gmail.com>

Kreta\Component\Project\Model\IssuePriority:
    exclusion_policy: ALL
    relations:
        -
            rel: issue_priorities
            href:
                route: get_projects_issue_priorities
                parameters:
                    projectId: expr(object.getProject().getId())
                absolute: true
            exclusion:
                groups: [issuePriorityList, issuePriority]
        -
            rel: project
            href:
                route: get_project
                parameters:
                    projectId: expr(object.getProject().getId())
                absolute: true
            exclusion:
                groups: [issuePriorityList, issuePriority]
    properties:
        id:
            expose: true
            groups: [projectList, project, issueList, issue, issuePriorityList, issuePriority]
        name:
            expose: true
            groups: [projectList, project, issueList, issue, issuePriorityList, issuePriority]
