# This file belongs to Kreta.
# The source code of application includes a LICENSE file
# with all information about license.
#
# @author benatespina <benatespina@gmail.com>
# @author gorkalaucirica <gorka.lauzirika@gmail.com>

imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: doctrine.yml }
    - { resource: @KretaApiBundle/Resources/config/app/config.yml }

parameters:
    assetic.ruby.bin: "%ruby_bin%"
    assetic.filter.compass.images_dir: "%kernel.root_dir%/Resources/sprites"
    assetic.filter.compass.http_path:  "/"
    assetic.filter.compass.generated_images_path: "%kernel.root_dir%/../web/images/"

framework:
    translator: { fallback: "%locale%" }
    secret: "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_proxies: ~
    session: ~
    fragments: ~
    http_method_override: true

twig:
    debug: "%kernel.debug%"
    strict_variables: "%kernel.debug%"

assetic:
    debug: "%kernel.debug%"
    use_controller: false
    bundles:
        - KretaWebBundle
        - FOSUserBundle
    filters:
        cssrewrite: ~
        compass:
            load_paths:
                - '%kernel.root_dir%/vendor/zurb/foundation/scss'
            bin: "%compass_route%"

swiftmailer:
    transport:  %mailer_transport%
    encryption: %mailer_encryption%
    port:       %mailer_port%
    host:       %mailer_host%
    username:   %mailer_user%
    password:   %mailer_password%
    spool:      { type: memory }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Kreta\Component\User\Model\User
    registration:
        confirmation:
            enabled: true

hwi_oauth:
    connect:
        account_connector: kreta_user.user_provider
    firewall_name: main
    fosub:
        username_iterations: 30
        properties:
            bitbucket: bitbucket_id
            github: github_id
    resource_owners:
        github:
            type: github
            client_id: %oauth.github.client_id%
            client_secret: %oauth.github.client_secret%
        bitbucket:
            type: bitbucket
            client_id: %oauth.bitbucket.client_id%
            client_secret: %oauth.bitbucket.client_secret%

knp_gaufrette:
    adapters:
        kreta_image_users:
            local:
                directory: %kernel.root_dir%/../web/media/image
                create: true
        kreta_image_projects:
            local:
                directory: %kernel.root_dir%/../web/media/image
                create: true
    filesystems:
        kreta_image_users:
            adapter: %users.image.uploader.filesystem%
        kreta_image_projects:
            adapter: %projects.image.uploader.filesystem%

liip_imagine:
    loaders:
        default:
            filesystem:
                data_root: %kernel.root_dir%/../web/media/image
    filter_sets:
        kreta_small:
            filters:
                thumbnail: { size: [150, 150], mode: outbound }
        kreta_medium:
            filters:
                thumbnail: { size: [240, 180], mode: outbound }
        kreta_large:
            filters:
                thumbnail: { size: [640, 480], mode: outbound }

sensio_framework_extra:
    view:
        annotations: false

doctrine_migrations: ~
