# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    kreta.task_manager.graphql.resolver.type:
        class: Kreta\SharedKernel\Infrastructure\Http\GraphQl\OverblogGraphQlBundle\OverblogGraphQlBundleResolver
        arguments:
            - "@overblog_graphql.type_resolver"
