# This file belongs to Kreta.
# The source code of application includes a LICENSE file
# with all information about license.
#
# @author benatespina <benatespina@gmail.com>
# @author gorkalaucirica <gorka.lauzirika@gmail.com>

Kreta\Component\Workflow\Model\StatusTransition:
    type: entity
    repositoryClass: Kreta\Component\Workflow\Repository\StatusTransitionRepository
    table: status_transition
    id:
        id:
            type: string
            generator:
                strategy: UUID
    fields:
        name:
            type: string
            length: 100
    manyToOne:
        workflow:
            targetEntity: Kreta\Component\Workflow\Model\Interfaces\WorkflowInterface
            inversedBy: statusTransitions
            joinColumn:
                name: workflow_id
                referencedColumnName: id
                onDelete: CASCADE
        state:
            targetEntity: Kreta\Component\Workflow\Model\Interfaces\StatusInterface
            joinColumn:
                name: status_transitions_state
                referencedColumnName: id
                onDelete: CASCADE
    manyToMany:
        initialStates:
            targetEntity: Kreta\Component\Workflow\Model\Interfaces\StatusInterface
            inversedBy: transitions
            joinTable:
                name: status_transitions_initial
                joinColumns:
                    status_transition_id:
                        referencedColumnName: id
                        onDelete: CASCADE
                inverseJoinColumns:
                    status_id:
                        referencedColumnName: id
                        onDelete: CASCADE
