# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    kreta.identity_access.action.user:
        class: Kreta\IdentityAccess\Infrastructure\Ui\Http\Action\UserAction
        arguments:
            - "@security.authorization_checker"
            - "@security.token_storage"

    kreta.identity_access.action.sign_up:
        class: Kreta\IdentityAccess\Infrastructure\Ui\Http\Action\SignUpAction
        arguments:
            - "@bengor_user.user.by_invitation_token_query"
            - "@bengor_user.user.symfony_data_transformer"
            - "@form.factory"
            - "@kreta.identity_access.command_bus"
            - "@session.flash_bag"
            - "@translator"
            - "@security.authentication.guard_handler"
            - "@bengor_user.user.form_login_authenticator"
            - "@templating.engine.twig"
