# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    kreta.notifier.event_listener.projector:
        class: Kreta\Notifier\Infrastructure\Symfony\EventListener\ProjectorEventListener
        arguments:
            -
                - "@kreta.notifier.projection.event_handler.user_signed_up"
                - "@kreta.notifier.projection.event_handler.user_received_notification"
                - "@kreta.notifier.projection.event_handler.user_read_notification"
                - "@kreta.notifier.projection.event_handler.user_unread_notification"
        tags:
            -
                name: kernel.event_listener
                event: kernel.request
                method: onKernel
            -
                name: kernel.event_listener
                event: console.command
                method: onKernel
