# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    kreta.notifier.command_handler.publish_notification:
        class: Kreta\Notifier\Application\Command\Notification\PublishNotificationHandler
        arguments:
            - "@kreta.notifier.repository.notification"
            - "@kreta.notifier.repository.user"
        tags:
            -
                name: command_handler
                handles: Kreta\Notifier\Application\Command\Notification\PublishNotificationCommand

    kreta.notifier.command_handler.mark_as_read_notification:
        class: Kreta\Notifier\Application\Command\Notification\MarkAsReadNotificationHandler
        arguments:
            - "@kreta.notifier.repository.notification"
            - "@kreta.notifier.repository.user"
        tags:
            -
                name: command_handler
                handles: Kreta\Notifier\Application\Command\Notification\MarkAsReadNotificationCommand

    kreta.notifier.command_handler.mark_as_unread_notification:
        class: Kreta\Notifier\Application\Command\Notification\MarkAsUnreadNotificationHandler
        arguments:
            - "@kreta.notifier.repository.notification"
            - "@kreta.notifier.repository.user"
        tags:
            -
                name: command_handler
                handles: Kreta\Notifier\Application\Command\Notification\MarkAsUnreadNotificationCommand
