# This file belongs to Kreta.
# The source code of application includes a LICENSE file
# with all information about license.
#
# @author benatespina <benatespina@gmail.com>
# @author gorkalaucirica <gorka.lauzirika@gmail.com>

Kreta\Component\Issue\Model\Issue:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [title, project]
            message: 'An issue with identical title is already exists in this project'
    properties:
        title:
            - NotBlank: ~
        type:
            - NotBlank: ~
        assignee:
            - NotBlank: ~
        priority:
            - NotBlank: ~
        project:
            - NotBlank: ~
