bazinga_hateoas:
    metadata:
        cache: file
        file_cache:
            dir: %kernel.cache_dir%/hateoas

fos_oauth_server:
    db_driver: orm
    access_token_class: Kreta\Bundle\ApiBundle\Model\AccessToken
    auth_code_class: Kreta\Bundle\ApiBundle\Model\AuthCode
    client_class: Kreta\Bundle\ApiBundle\Model\Client
    refresh_token_class: Kreta\Bundle\ApiBundle\Model\RefreshToken
    service:
        user_provider: kreta_user.user_provider
        options:
            supported_scopes: user

fos_rest:
    routing_loader:
        include_format: false
        default_format: json
    param_fetcher_listener: true
    body_listener:
        array_normalizer: fos_rest.normalizer.camel_keys
    view:
        view_response_listener: force

jms_serializer:
    metadata:
        directories:
            kreta-comment:
                namespace_prefix: "Kreta\\Component\\Comment"
                path: "@KretaApiBundle/Resources/config/serializer"
            kreta-core:
                namespace_prefix: "Kreta\\Component\\Core"
                path: "@KretaApiBundle/Resources/config/serializer"
            kreta-issue:
                namespace_prefix: "Kreta\\Component\\Issue"
                path: "@KretaApiBundle/Resources/config/serializer"
            kreta-media:
                namespace_prefix: "Kreta\\Component\\Media"
                path: "@KretaApiBundle/Resources/config/serializer"
            kreta-notification:
                namespace_prefix: "Kreta\\Component\\Notification"
                path: "@KretaApiBundle/Resources/config/serializer"
            kreta-project:
                namespace_prefix: "Kreta\\Component\\Project"
                path: "@KretaApiBundle/Resources/config/serializer"
            kreta-user:
                namespace_prefix: "Kreta\\Component\\User"
                path: "@KretaApiBundle/Resources/config/serializer"
            kreta-workflow:
                namespace_prefix: "Kreta\\Component\\Workflow"
                path: "@KretaApiBundle/Resources/config/serializer"
            FOSUserBundle:
                namespace_prefix: "FOS\\UserBundle"
                path: "@KretaApiBundle/Resources/FOSUserBundle/serializer"

nelmio_api_doc: ~

nelmio_cors:
    paths:
        '^/':
            allow_origin: ['*']
            allow_headers: ['X-Custom-Auth']
            allow_methods: ['POST', 'PUT', 'DELETE']
            max_age: 3600

sensio_framework_extra:
    view:
        annotations: true
