# This file belongs to Kreta.
# The source code of application includes a LICENSE file
# with all information about license.
#
# @author benatespina <benatespina@gmail.com>
# @author gorkalaucirica <gorka.lauzirika@gmail.com>

services:
    kreta_workflow.repository.workflow:
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        class: %kreta_workflow.repository_workflow.class%
        arguments: [%kreta_workflow.workflow.class%]
    kreta_workflow.repository.status:
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        class: %kreta_workflow.repository_status.class%
        arguments: [%kreta_workflow.status.class%]
    kreta_workflow.repository.status_transition:
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        class: %kreta_workflow.repository_status_transition.class%
        arguments: [%kreta_workflow.status_transition.class%]
