# This file belongs to Kreta.
# The source code of application includes a LICENSE file
# with all information about license.
#
# @author benatespina <benatespina@gmail.com>
# @author gorkalaucirica <gorka.lauzirika@gmail.com>

Kreta\Component\Notification\Model\Notification:
    exclusion_policy: ALL
    relations:
        -
            rel: notifications
            href:
                route: get_notifications
                absolute: true
            exclusion:
                groups: [notificationList, notification]
        -
            rel: projects
            href:
                route: get_projects
                absolute: true
            exclusion:
                groups: [notificationList, notification]
    properties:
        id:
            expose: true
            groups: [notificationList, notification]
        description:
            expose: true
            groups: [notificationList, notification]
        date:
            expose: true
            groups: [notificationList, notification]
        read:
            expose: true
            groups: [notificationList, notification]
        resourceUrl:
            expose: true
            groups: [notificationList, notification]
        title:
            expose: true
            groups: [notificationList, notification]
        type:
            expose: true
            groups: [notificationList, notification]
        webUrl:
            expose: true
            groups: [notificationList, notification]
