# This file belongs to Kreta.
# The source code of application includes a LICENSE file
# with all information about license.
#
# @author benatespina <benatespina@gmail.com>
# @author gorkalaucirica <gorka.lauzirika@gmail.com>

services:
#### SECURITY ####
    kreta_project.voter.project:
        class: %kreta_project.security_project_voter.class%
        public: false
        tags:
           - { name: security.voter }

#### UPLOADER ####
    kreta_project.uploader.image_project:
        class: %kreta_media.uploader_media.class%
        arguments: [@kreta_project.uploader_filesystem.image_project]
    kreta_project.uploader_filesystem.image_project:
        class: Gaufrette\Filesystem
        factory_service: knp_gaufrette.filesystem_map
        factory_method: get
        arguments: [%projects.image.uploader.filesystem%]


#    kreta_annotation.metadata.annotation_driver:
#        class: %kreta_annotation.metadata.annotation_driver.class%
#        public: false
#        arguments: ['@annotation_reader']
#    kreta_annotation.metadata_factory:
#        class: %kreta_annotation.metadata_factory.class%
#        public: false
#        arguments: ['@kreta_annotation.metadata.annotation_driver']
#
