# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

doctrine:
    dbal:
        dbname: "%task_manager_database_name%_test"
        host: 127.0.0.1
        password: ~

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

services:
    kreta.task_manager.event_listener.authentication:
        class: Kreta\TaskManager\Tests\Double\Infrastructure\Symfony\EventListener\DummyAuthenticationListener
        arguments:
            - "@security.token_storage"
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
